version: "3.8"

services:     
  otel-collector:
    platform: linux/amd64
    image: otel/opentelemetry-collector-contrib:nightly
    environment:
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      ZTNA_TARGET: "${ZTNA_TARGET}"
    volumes:
      - /data/otel/otel-config.yaml:/etc/otel/config.yaml
    ports:
      - "4318:4318"   # OTLP/HTTP receiver
      - "4317:4317"   # OTLP/gRPC receiver (opcional)
      - "13133:13133" # Health check extension