services:     
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.180.0
    container_name: otel-ztna
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    environment:
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      ZTNA_TARGET: "${ZTNA_TARGET}"
    volumes:
      - ./otel/config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4318:4318"   # OTLP/HTTP receiver (Kong → Collector)
      - "4317:4317"   # OTLP/gRPC receiver (opcional)
      - "13133:13133" # Health check extension